name: pdfview
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  excel: ^4.0.6
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.4
  pdfx: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - assets\images\pdfimg.png
    
